# Import the relevant libraries

In [1]:
import numpy as np

## Addition

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [4]:
#we are not allowed to add matrices with different dimensions 
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [18]:
#m3 = np.array([[5,3],[-2,4]])
m3 = np.array([[5,3,11],[-2,4,33]])
m3

array([[ 5,  3, 11],
       [-2,  4, 33]])

In [19]:
m1 + m3

array([[10, 15, 17],
       [-5,  4, 47]])

### Addition of vectors

In [7]:
#we are not allowed to add vectors with different length
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [16]:
#v3 = np.array([1,2,3])
v3 = np.array([11,22,33,44,55])
v3


array([11, 22, 33, 44, 55])

In [17]:
v1+v3

array([12, 24, 36, 48, 60])

### Exceptions (addition with a scalar)

In [10]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [20]:
v1

array([1, 2, 3, 4, 5])

In [21]:
v1 + 1

array([2, 3, 4, 5, 6])

In [22]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [23]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])